#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Real corpus → PDW input (terms.jsonl + corpus.jsonl). Zero LLM calls.

Input:
  --docs      directory (*.txt / *.md, one document per file) or jsonl ({"doc_id","text"[,"domain"]})
  --glossary  optional: csv (term,definition[,standard][,domain]) or jsonl ({"term","definition",...}) -- manual/document term list, used as gloss_gold
  --min-tf    minimum corpus term frequency for candidate terms (default 5); candidates = glossary terms ∪ words and bigrams in corpus with tf≥min_tf (not filtered by rarity, see ALGORITHM I7/E14)
  --max-terms candidate cap (truncated by descending tf; glossary terms always retained)
  --k-ctx     max number of context sentences kept per term (random sampling, default 24)
  --lang      en | zh (zh requires pre-tokenization: text pre-segmented with spaces, or use --glossary to run glossary terms only)
Output:
  <out>/terms.jsonl   {"id","term","lang","contexts","spans":null,"gloss_gold"?,"labels":{"source","tf","df","n_words","doc_ids","domain"?,"in_glossary"},"qa":[]}
  <out>/corpus.jsonl  {"doc_id","text"}
  <out>/PREP_REPORT.md
Next steps: QA is generated by run_eqa.py --from-gold (if gold available) or default (no gold); weights computed by run_pdw.py; overall pipeline via run_local.py (dataset entries in README §7).
"""
import argparse, csv, glob, json, os, random, re, sys
from collections import Counter, defaultdict

STOP = set("""a an the and or but if then of to in on at by for with from as is are was were be been being it its this that these those
there here which who whom whose what when where why how all any both each few more most other some such no nor not only own same so than too very
can will just should now shall may might must would could do does did done have has had having i you he she we they me him her us them my your his
our their mine yours hers ours theirs am about above after again against also am among because before below between during into over under until up
down out off per via upon within without one two three four five six seven eight nine ten first second third new use used using""".split())
SENT = re.compile(r"(?<=[.!?;:])\s+(?=[A-Z(\"“])|\n{2,}")
TOK = re.compile(r"[A-Za-z][A-Za-z0-9\-']*")


def sentences(text):
    out = []
    for para in text.split("\n"):
        para = para.strip()
        if not para:
            continue
        for s in SENT.split(para):
            s = s.strip()
            if 6 <= len(s.split()) <= 80:
                out.append(s)
    return out


def load_docs(path):
    docs = []
    if os.path.isdir(path):
        for f in sorted(glob.glob(os.path.join(path, "**", "*.*"), recursive=True)):
            if f.lower().endswith((".txt", ".md")):
                docs.append({"doc_id": os.path.relpath(f, path), "text": open(f, encoding="utf-8", errors="ignore").read()})
    else:
        for l in open(path, encoding="utf-8"):
            if l.strip():
                docs.append(json.loads(l))
    return docs


def load_glossary(path):
    if not path:
        return []
    rows = []
    if path.endswith(".jsonl"):
        for l in open(path, encoding="utf-8"):
            if l.strip():
                rows.append(json.loads(l))
    else:
        for r in csv.DictReader(open(path, encoding="utf-8")):
            rows.append(r)
    out = []
    for r in rows:
        t = (r.get("term") or "").strip(); d = (r.get("definition") or r.get("gloss") or "").strip()
        if t and d:
            out.append({"term": t, "definition": d, "standard": (r.get("standard") or "").strip() or None, "domain": r.get("domain")})
    return out


def find_all(term, sents):
    pat = re.compile(r"(?<![A-Za-z0-9_])" + re.escape(term) + r"(?![A-Za-z0-9_])", re.IGNORECASE)
    return [s for s in sents if pat.search(s)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--docs", required=True)
    ap.add_argument("--glossary")
    ap.add_argument("--out", required=True)
    ap.add_argument("--min-tf", type=int, default=5)
    ap.add_argument("--max-terms", type=int, default=300)
    ap.add_argument("--k-ctx", type=int, default=24)
    ap.add_argument("--lang", default="en")
    ap.add_argument("--source", default="real")
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args()
    rng = random.Random(a.seed)
    os.makedirs(a.out, exist_ok=True)
    docs = load_docs(a.docs); gl = load_glossary(a.glossary)
    sents_by_doc = {d["doc_id"]: sentences(d["text"]) for d in docs}
    all_sents = [(d["doc_id"], s) for d in docs for s in sents_by_doc[d["doc_id"]]]
    # Candidates: unigrams + bigrams (not filtered by rarity)
    tf, df = Counter(), Counter()
    for d in docs:
        toks = [t.lower() for t in TOK.findall(d["text"])]
        uni = [t for t in toks if t not in STOP and len(t) > 2]
        bi = [f"{x} {y}" for x, y in zip(toks, toks[1:]) if x not in STOP and y not in STOP and len(x) > 2 and len(y) > 2]
        c = Counter(uni) + Counter(bi)
        tf.update(c); df.update(set(c))
    cands = [t for t, n in tf.most_common() if n >= a.min_tf]
    gl_terms = {g["term"].lower(): g for g in gl}
    cands = [t for t in cands if t not in gl_terms][: max(0, a.max_terms - len(gl_terms))]
    terms = list(gl_terms) + cands
    n_written = 0
    with open(os.path.join(a.out, "terms.jsonl"), "w", encoding="utf-8") as f:
        for t in terms:
            g = gl_terms.get(t)
            surface = g["term"] if g else t
            hits = [(did, s) for did, s in all_sents if re.search(r"(?<![A-Za-z0-9_])" + re.escape(surface) + r"(?![A-Za-z0-9_])", s, re.I)]
            if g and g.get("definition"):
                hits = [(did, s) for did, s in hits if g["definition"][:60].lower() not in s.lower()]  # Remove the definition sentence itself
            if len(hits) < 2:
                continue
            rng.shuffle(hits)
            ctx = [s for _, s in hits[: a.k_ctx]]
            rec = {"id": f"{a.source}:{surface}", "term": surface, "lang": a.lang, "contexts": ctx, "spans": None,
                   "labels": {"source": a.source, "tf": tf.get(t, len(hits)), "df": df.get(t, len({d for d, _ in hits})),
                              "n_words": len(surface.split()), "doc_ids": sorted({d for d, _ in hits})[:20],
                              "in_glossary": bool(g), "domain": (g or {}).get("domain"), "variant": "main"},
                   "qa": []}
            if g:
                rec["gloss_gold"] = g["definition"]
                if g.get("standard"):
                    rec["labels"]["standard_meaning"] = g["standard"]
            f.write(json.dumps(rec, ensure_ascii=False) + "\n"); n_written += 1
    with open(os.path.join(a.out, "corpus.jsonl"), "w", encoding="utf-8") as f:
        for d in docs:
            f.write(json.dumps({"doc_id": d["doc_id"], "text": d["text"]}, ensure_ascii=False) + "\n")
    rep = [f"# Corpus Preparation Report", f"- {len(docs)} documents, {len(all_sents)} sentences", f"- Glossary terms {len(gl_terms)}, candidate terms {len(cands)} (tf≥{a.min_tf}), wrote {n_written} entries (≥2 context sentences)",
           f"- Next: `run_eqa.py --from-gold` (if gold available) generates low-context questions; `run_local.py` dataset entries see README §7"]
    open(os.path.join(a.out, "PREP_REPORT.md"), "w", encoding="utf-8").write("\n".join(rep) + "\n")
    print("\n".join(rep), file=sys.stderr)


if __name__ == "__main__":
    main()