#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Baseline B-self: LLM self-report ("ask the reader directly"). Two forms, neither performs any behavioral measurement:
  per-term   gives the reader k context snippets, asks "does the usage of this term here match your expectation", outputs a 0-1 divergence score + one-sentence note → self_report
  corpus     gives the reader a corpus sample (per document), has it list terms "used in a non-standard sense or unrecognized" → nominations per term / number of documents → self_extract
Also includes B-ref: generates "generic usage reference sentences" for the embedding-drift baseline (reference_sentences.jsonl, n sentences of ordinary English usage per term; returns NONE for invented terms).

Usage: python3 run_selfreport.py --terms data/synth_terms.jsonl --corpus data/synth_corpus.jsonl --out data/sonnet/baselines_synth.jsonl --ref-out data/refs_synth.jsonl
Environment variables same as run_pdw.py (LLM_* reader; REF sentences generated by DRAFT_MODEL, falls back to reader if unset).
"""
import argparse, json, os, re, sys
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from pdwlib.llm import client_from_env
from pdwlib.text import extract_json, tokens

PER_TERM = ("SELF_REPORT. Below are usages of the term \"{term}\" from one organisation's internal documents.\n{contexts}\n\n"
            "Question: in these documents, is \"{term}\" used the way you would normally expect the word to be used, or in a "
            "special in-house sense (or a sense you do not know)? Answer as JSON only: "
            "{{\"divergence\": <number 0-1; 0 = exactly the usual meaning, 1 = a completely different or unknown meaning>, "
            "\"note\": \"one sentence\"}}")
CORPUS = ("SELF_EXTRACT. Read this internal document. List every word or short phrase that is used here in a non-standard, "
          "in-house sense, OR that you do not recognise at all. Output a JSON list of strings (the surface forms exactly as they "
          "appear), nothing else. If none, output [].\n\nDOCUMENT:\n{doc}")
REF = ("REF_SENTENCES. Write {n} ordinary English sentences, from everyday or general-professional contexts (news, textbooks, "
       "casual conversation), that use the word \"{term}\" in its usual, most common meaning. One sentence per line, no numbering. "
       "If \"{term}\" is not a real English word or established term, output exactly NONE.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--terms", required=True)
    ap.add_argument("--corpus", help="jsonl {doc_id, text}; if given, run corpus extraction")
    ap.add_argument("--out", required=True)
    ap.add_argument("--ref-out", help="generate generic reference sentences (for embedding-drift baseline)")
    ap.add_argument("--n-ref", type=int, default=8)
    ap.add_argument("--k", type=int, default=8)
    ap.add_argument("--main-only", action="store_true", help="process only labels.variant == main")
    ap.add_argument("--mock", action="store_true")
    ap.add_argument("--cache-dir", default="data/cache")
    a = ap.parse_args()
    os.makedirs(a.cache_dir, exist_ok=True)
    reader = client_from_env("LLM", mock=a.mock, cache_path=os.path.join(a.cache_dir, "reader.jsonl"))
    drafter = reader if (a.mock or not os.environ.get("DRAFT_MODEL")) else client_from_env("DRAFT", cache_path=os.path.join(a.cache_dir, "draft.jsonl"))
    entries = [json.loads(l) for l in open(a.terms, encoding="utf-8") if l.strip()]
    if a.main_only:
        entries = [e for e in entries if e.get("labels", {}).get("variant", "main") == "main"]

    # per-term self-report
    reqs = [dict(prompt=PER_TERM.format(term=e["term"], contexts="\n".join(f"- {c}" for c in e["contexts"][:a.k])), max_tokens=120) for e in entries]
    outs = []
    for i in range(0, len(reqs), 200):
        outs.extend(reader.complete_many(reqs[i:i + 200]))
        print(f"\r[self] {min(i+200, len(reqs))}/{len(reqs)}", end="", file=sys.stderr)
    print(file=sys.stderr)
    rec = {}
    for e, o in zip(entries, outs):
        j = extract_json(o) or {}
        try:
            d = float(j.get("divergence"))
        except Exception:  # noqa
            m = re.search(r"([01](?:\.\d+)?)", o or "")
            d = float(m.group(1)) if m else float("nan")
        rec[e["id"]] = {"id": e["id"], "term": e["term"], "labels": e.get("labels", {}), "self_report": d, "self_note": j.get("note")}

    # corpus-level extraction
    if a.corpus:
        docs = [json.loads(l) for l in open(a.corpus, encoding="utf-8") if l.strip()]
        outs = reader.complete_many([dict(prompt=CORPUS.format(doc=d["text"][:6000]), max_tokens=400) for d in docs])
        nominated = {}
        for o in outs:
            try:
                lst = json.loads(re.search(r"\[.*\]", o or "[]", flags=re.S).group(0))
            except Exception:  # noqa
                lst = []
            for x in lst:
                nominated[str(x).strip().lower()] = nominated.get(str(x).strip().lower(), 0) + 1
        for e in entries:
            t = e["term"].lower()
            hits = sum(v for k, v in nominated.items() if k == t or re.search(r"(?<![a-z0-9_])" + re.escape(t) + r"(?![a-z0-9_])", k))
            rec[e["id"]]["self_extract"] = hits / max(1, len(docs))
            rec[e["id"]]["self_extract_hits"] = hits
        print(f"[extract] docs={len(docs)} distinct nominations={len(nominated)}", file=sys.stderr)

    with open(a.out, "w", encoding="utf-8") as f:
        for r in rec.values():
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    # reference sentences
    if a.ref_out:
        seen, uniq = set(), []
        for e in entries:
            if e["term"] not in seen:
                seen.add(e["term"]); uniq.append(e["term"])
        outs = drafter.complete_many([dict(prompt=REF.format(n=a.n_ref, term=t), max_tokens=400) for t in uniq])
        with open(a.ref_out, "w", encoding="utf-8") as f:
            for t, o in zip(uniq, outs):
                sents = [] if (o or "").strip().upper().startswith("NONE") else [s.strip() for s in (o or "").splitlines() if s.strip() and t.lower() in s.lower()]
                f.write(json.dumps({"term": t, "reference": sents}, ensure_ascii=False) + "\n")
        print(f"[ref] {len(uniq)} terms → {a.ref_out}", file=sys.stderr)
    print(f"[done] {len(rec)} → {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()